#!/bin/bash

set -e -u

if [[ $# -ne 1 ]]; then
    echo "Usage: ${0##*/} <video-file>"
    echo "Press 's' during playback to save a screenshot. Works with -vo vdpau."
    echo "If nothing happens when you press 's', you may want to add the following line to ~/.mplayer/input.conf:"
    echo "s get_time_pos"
    exit 0
fi

screenshot_dir=~/.mplayer/screenshots

mkdir -p "$screenshot_dir"

next_file() { (
    cd "$screenshot_dir"
    for file in $1???.$2; do last=$file; done
    if [[ $last = $1\?\?\?.$2 ]]; then
        printf "%s000.%s" "$1" "$2"
    else
        printf "%s%03d.%s" "$1" \
            $(( 1 + $(echo $last | sed "s/$1\([0-9]*\)\.$2/\1/") )) "$2"
    fi
) }

capture_audio() {
    echo 'Not implemented!'
    return 1
    # The following code is broken due to imprecisions.
    target=$1
    start=$2
    duration=$3
    tmp=/tmp/foo$RANDOM$RANDOM$RANDOM.wav
    tmp2=/tmp/foo$RANDOM$RANDOM$RANDOM-2.wav
    echo "Extracting audio from time ${start}s to ${time}s (${duration}s in total)..."
    ffmpeg -y -ss "$time" -t "$duration" -i "$1" -vn "$tmp" &>/dev/null && \
        ffmpeg -y -t "$duration" -i "$tmp" -vn -acodec copy "$tmp2" &>/dev/null && \
        oggenc -q 4 "$tmp2" -o "$target" &>/dev/null && \
        rm "$tmp" "$tmp2"
}

mode=screenshot
start=
while read -r line; do
    time=$(printf '%s' "$line" | sed 's/^ANS_TIME_POSITION=\(.*\)$/\1/;t;d')
    switch_mode=$(printf '%s' "$line" | sed 's/^ANS_PERCENT_POSITION=\(.*\)$/\1/;t;d')
    [[ $time || $switch_mode ]] || continue

    if [[ $switch_mode ]]; then
        if [[ $mode = screenshot ]]; then
            mode=audio
            echo 'Switched to audio mode!'
            continue
        else
            mode=screenshot
            start=
            echo 'Switched to screenshot mode!'
            continue
        fi
    fi

    if [[ $mode = screenshot ]]; then
        target=$(next_file screen png)
        echo "Saving screenshot at time ${time}s..."
        if ffmpeg -ss "$time" -vframes 1 -i "$1" "$screenshot_dir/$target" &>/dev/null; then
            echo "Saved screenshot: $screenshot_dir/$target"
        else
            echo "Could not save screenshot. An error occured."
        fi
    else
        if [[ ! $start ]]; then
            start=$time
            echo "Starting audio capture at time ${time}s..."
        else
            target=$(next_file audio ogg)
            duration=$( echo "$time - $start" | bc )
            echo "Extracting audio from time ${start}s to ${time}s (${duration}s in total)..."
            echo ffmpeg -ss "$time" -t "$duration" -i "$1" -vn -acodec copy "$screenshot_dir/$target"
            if capture_audio "$screenshot_dir/$target" $start $duration; then
                echo "Saved audio: $screenshot_dir/$target"
            else
                echo "Could not save audio. An error occured."
            fi
        fi
    fi
done < <(/usr/bin/mplayer "$1")

exit 0
